@ArticleService_HostAddress = http://localhost:5023

POST {{ArticleService_HostAddress}}/api/articles/Europe
Content-Type: application/json

{
  "title": "New train service opens in Denmark",
  "content": "A new train connection has opened."
}
